//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QtwoGOAL
    {
        public int qtwogoalID { get; set; }
        public Nullable<int> qtwogoalValue { get; set; }
        public Nullable<int> agoalID { get; set; }
    }
}
